sudo: required
services:
  - docker

before_install:
  - docker build -t client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true client-test npm run test

after_success:
  - docker build -t devil356/multi-client ./client
  - docker build -t devil356/multi-nginx ./nginx
  - docker build -t devil356/multi-server ./server
  - docker build -t devil356/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push devil356/multi-client
  - docker push devil356/multi-nginx
  - docker push devil356/multi-server
  - docker push devil356/multi-worker
