sudo: required
services:
  - docker

before_install:
  - docker build -t client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true client-test npm run test

after_success:
  - docker build -t devil356/multi-client ./client
  - docker build -t devil356/multi-nginx ./nginx
  - docker build -t devil356/multi-server ./server
  - docker build -t devil356/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push devil356/multi-client
  - docker push devil356/multi-nginx
  - docker push devil356/multi-server
  - docker push devil356/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-943493414152"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
